name: Selenium Weekly CI

on:
  schedule:
    - cron: "0 1 * * MON"
  workflow_dispatch:

jobs:
  check_format:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Install shards
        run: shards install
      - name: Format
        run: crystal tool format --check
      - name: Crystal Ameba Linter
        run: ./bin/ameba
  verify-chrome:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            crystal: nightly
          - os: windows-latest
            crystal: nightly
          - os: macos-latest
            crystal: nightly
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal_version }}
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
        if: matrix.os == 'windows-latest'
      - name: Install dependencies
        run: shards install --ignore-crystal-version --skip-executables --skip-postinstall
      - name: Run tests
        run: crystal spec --tag "~chrome"
        env:
          SELENIUM_BROWSER: chrome
